name: bookmarks
description: A Flutter application to manage bookmarks.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Rubik Mono One
      fonts:
        - asset: assets/fonts/RubikMonoOne-Regular.ttf
    - family: Rubik-Light
      fonts:
        - asset: assets/fonts/Rubik-Light.ttf
